import Link from "next/link";
import { BarChart3, AlertTriangle } from "lucide-react";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-grey">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6">
          <Link href="/" className="flex items-center gap-2">
            <BarChart3 className="h-6 w-6 text-navy" />
            <span className="font-semibold text-navy">InvestNow</span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
        <div className="mb-8 flex items-center gap-3">
          <AlertTriangle className="h-6 w-6 text-amber-500" />
          <h1 className="text-2xl font-bold text-navy">Investment Disclaimer</h1>
        </div>

        <div className="prose prose-sm max-w-none text-navy/70 space-y-6">
          <div className="rounded-xl border-2 border-amber-200 bg-amber-50 p-5">
            <p className="font-semibold text-amber-800">
              Important: This is educational information only — not regulated financial advice.
            </p>
            <p className="mt-2 text-amber-700">
              InvestNow is NOT an authorised Financial Services Provider (FSP) under the
              Financial Advisory and Intermediary Services Act, 37 of 2002 (FAIS Act).
              We are not licensed to provide regulated financial advice.
            </p>
          </div>

          <section>
            <h2 className="text-base font-semibold text-navy">1. Educational Information Only</h2>
            <p>
              All content generated by InvestNow — including portfolio guidance, stock explanations,
              and investment insights — is provided for educational and informational purposes only.
              Nothing on this platform constitutes regulated financial advice, a recommendation to buy
              or sell any security, or an invitation to invest.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-navy">2. No Fiduciary Relationship</h2>
            <p>
              Your use of InvestNow does not create a fiduciary relationship between you and
              InvestNow. We are not your financial advisor, investment manager, or stockbroker.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-navy">3. Investment Risk</h2>
            <p>
              All investments carry risk. The value of investments can go down as well as up.
              Past performance is not a reliable indicator of future results. You may receive
              back less than you invested. Always consider your own financial situation,
              risk tolerance, and investment objectives before making any investment decision.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-navy">4. Do Your Own Research</h2>
            <p>
              Before making any investment, you should conduct your own thorough research
              and, where appropriate, seek advice from an authorised and licensed financial
              advisor registered with the Financial Sector Conduct Authority (FSCA).
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-navy">5. AI-Generated Content</h2>
            <p>
              Portfolio guidance and stock explanations are generated by artificial intelligence
              (Claude by Anthropic). AI models can make mistakes. Always verify information
              from independent sources before acting on it.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-navy">6. Market Data</h2>
            <p>
              Price data may be delayed by up to 15 minutes. InvestNow makes no representations
              about the accuracy, completeness, or timeliness of market data provided.
            </p>
          </section>

          <p className="text-xs text-navy/40">Last updated: May 2026</p>
        </div>

        <div className="mt-8 flex gap-4 text-sm">
          <Link href="/privacy" className="text-navy/60 hover:text-navy">Privacy Policy</Link>
          <Link href="/terms" className="text-navy/60 hover:text-navy">Terms of Service</Link>
          <Link href="/" className="text-navy/60 hover:text-navy">Back to home</Link>
        </div>
      </main>
    </div>
  );
}
